# Applications to install

general:
  local_home: "{{ lookup('env', 'HOME') }}"

# homebrew


applications:
    - git
    # - tree
    # - curl
    # - wget
    # - vim
    #- maven java
    - openssl
   # - direnv need java
    

# Homebrew cask

cask:
    # - google-chrome
     - slack
    # - iterm2
    # - docker
    # - docker-compose
    # - vagrant
    #- virtualbox #causing issues
    #- emacs
    # - postman

github:  #currently working on
  - platform
  - consumer-ui
  - trizic-ops
  - containers
  - api-docs-advisor
  - api-docs-consumer
  - custodianservices
  - td-api-java-lib
  - client-billing
  - messaging-common


downloads:
  zoom:
    name: Zoom
    url: https://zoom.us/support/download?os=mac
    dest: "{{general.local_home}}/Downloads/zoom.pkg"
  # emacs:
  #   name: Emacs
  #   url: https://emacsformacosx.com/emacs-builds/Emacs-26.1-2-universal.dmg
  #   dest: "{{general.local_home}}/Downloads/emacs.dmg"

git_ssh_public_key: "~/.ssh/my_ssh_key.pub"




git_ssh_key: "~/.ssh/my_ssh_key"




