# Applications to install

general:
  local_home: "{{ lookup('env', 'HOME') }}"
  local_user: "{{ lookup('env', 'USER') }}"
  local_group: "{{ lookup('env', 'GROUP')}}"

# homebrew


applications:
    - git
    - tree
    - curl
    - wget
    - vim
    - maven
    - openssl
    - direnv 
    

# Homebrew cask

cask:
    - google-chrome
    - slack
    - iterm2
    - docker
    - docker-compose
    - vagrant
    - virtualbox #causing issues
    - emacs
    - postman
    - zoom
    - zoomus


filePaths:
  - ~/Documents/Trizic/
  - ~/Documents/Trizic/platform
  - ~/Documents/Trizic/consumer-ui
  - ~/Documents/Trizic/trizic-ops
  - ~/Documents/Trizic/containers
  - ~/jdk1.8

downloads:
  zoom:
    name: Zoom
    url: https://zoom.us/support/download?os=mac
    dest: "{{general.local_home}}/Downloads/zoom.pkg"
  # emacs:
  #   name: Emacs
  #   url: https://emacsformacosx.com/emacs-builds/Emacs-26.1-2-universal.dmg
  #   dest: "{{general.local_home}}/Downloads/emacs.dmg"

bouncy_url: http://www.bouncycastle.org/download/bcprov-jdk15on-160.jar
bouncy_download: /tmp/{{bouncy_jar}}
bouncy_jar: bcprov-jdk15on-160.jar

download_url: https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-macosx-x64.dmg
download_folder: ~/
java_name: "{{download_folder}}jdk1.8"
java_archive: "{{download_folder}}jdk-8u5.dmg" 

jce_download_url: http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
jce_folder: UnlimitedJCEPolicyJDK8
java_home: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home
jce_zip_file: jce.zip
java_header: 'Cookie:oraclelicense=accept-securebackup-cookie'

git_ssh_public_key: "~/.ssh/my_ssh_key.pub"

java_version: "8"
java_subversion: "191"


git_ssh_key: "~/.ssh/my_ssh_key"

dockPrograms:
  - slack
  - iterm
  - virtualbox
  - postman
  - docker
  - google-chrome




