# Applications to install

general:
  local_home: "{{ lookup('env', 'HOME') }}"
  local_user: "{{ lookup('env', 'USER') }}"
  local_group: "{{ lookup('env', 'GROUP')}}"

# homebrew


applications:
    - git
    # - tree
    # - curl
    # - wget
    # - vim
    #- maven java
    - openssl
   # - direnv need java
    

# Homebrew cask

cask:
    # - google-chrome
     - slack
    # - iterm2
    # - docker
    # - docker-compose
    # - vagrant
    #- virtualbox #causing issues
    #- emacs
    # - postman


filePaths:
  - ~/Documents/Trizic/
  - ~/Documents/Trizic/platform
  - ~/Documents/Trizic/consumer-ui
  - ~/Documents/Trizic/trizic-ops
  - ~/Documents/Trizic/containers
  - ~/jdk1.8

downloads:
  zoom:
    name: Zoom
    url: https://zoom.us/support/download?os=mac
    dest: "{{general.local_home}}/Downloads/zoom.pkg"
  # emacs:
  #   name: Emacs
  #   url: https://emacsformacosx.com/emacs-builds/Emacs-26.1-2-universal.dmg
  #   dest: "{{general.local_home}}/Downloads/emacs.dmg"

download_url: https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-macosx-x64.dmg
download_folder: ~/
java_name: "{{download_folder}}/jdk1.8/"
java_archive: "{{download_folder}}/jdk-8u5.dmg" 

git_ssh_public_key: "~/.ssh/my_ssh_key.pub"




git_ssh_key: "~/.ssh/my_ssh_key"




