# Applications to install

general:
  local_home: "{{ lookup('env', 'HOME') }}"

# homebrew


applications:
    - git
    - tree
    - curl
    - wget
    - vim
    #- maven java
    - openssl
   # - direnv need java
    

# Homebrew cask

cask:
    - google-chrome
    - slack
    - iterm2
    - docker
    - docker-compose
    - vagrant
    #- virtualbox #causing issues
    - emacs
    - postman

github:  #currently working on
  - platform
  - consumer-ui
  - trizic-ops
  - containers
  - api-docs-advisor
  - api-docs-consumer
  - custodianservices
  - td-api-java-lib
  - client-billing
  - messaging-common


downloads:
  zoom:
    name: Zoom
    url: https://zoom.us/support/download?os=mac
    dest: "{{general.local_home}}/Downloads/zoom.pkg"

git_ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDkElDSGp7Vyf6lSunx0eZuockAYkaC1m5GA+ZDia9G3gSw53Q
  Q99qIB0PK6bRoDCzrCGULlK3J9sRUbR6LUL6Rxo8l6AbbBhjXg/yV/xeNT3MQ/9u0O2ddglXnWz6FXw8gTLI3zVv5bToEa1sGlBVCuvXd8Qd+ERRp9N9rs2JQHpIIo8OlFk/b+DKWbGNznqr4C1hkEjKBLvxdjW+wdTW41Ocl31ioVjvdNhNAiJAEIiGfn0uCso7QhgFW/cOPOyGlnwOEBm+K9kyAAr3ddHa1O6uMkAFZad7fmMSSg2/pLKnkIRpvn0wPVoGdAhPWs1LRVzDAVSX6NYjU7O5MaJ81etqi0Oswjo9Kk2OmkrQoSZbJzQcpBsU07b8wiuPZ97Pn3TwKs2Eh08Uk0gFI5I0ZlYmO9h7siaxlXlqis2+QkMogNWKzAsKNWrpBstAmIPM+zMvQKMyM0QpZ9EeTWLXIg9JkLriSfvfITisgfhsX8ijTiaOBiNLKJ67lfrAn65kX9SfLHGabM0XMimCM78Bdkjdmn7rZNlBdseb8PzoSq6Fv/v7dQi4p8LTVP8CTRAGM01MfWkonRn3wOdaYPHYo+lQsgermLjgDgBEr5e4f7xBmXxiueO6kLx7nYkiBz1M2uQ8OZefJsxzt/QFmsHJ4ieayLtxGwhJpx0HK2lNrTw== s_moloney@aol.com




git_ssh_key: 
  -----BEGIN RSA PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEA5BJQ0hqe1cn+pUrp8dHmbqHJAGJGgtZuRgPmQ4mvRt4EsOd0EPfa
iAdDyum0aAws6whlC5StyfbEVG0ei1C+kcaPJegG2wYY14P8lf8XjU9zEP/btDtnXYJV51
s+hV8PIEyyN81b+W06BGtbBpQVQrr13fEHfhEUafTfa7NiUB6SCKPDpRZP2/gylmxjc56q
+AtYZBIygS78XY1vsHU1uNTnJd9YqFY73TYTQIiQBCIhn59LgrKO0IYBVv3DjzshpZ8DhA
ZvivZMgAK93XR2tTurjJABWWne35jEkoNv6Syp5CEab59MD1aBnQIT1rNS0VcwwFUl+jWI
1OzuTGifNXraotDrMI6PSpNjppK0KEmWyc0HKQbFNO2/MIrj2fez5908CrNhIdPFJNIBSO
SNGZWJjvYe7ImsZV5aorNvkJDKIDViswLCjVq6QbLQJiDzPszL0CjMjNEKWfRHk1i1yIPS
ZC64kn73yE4rIH4bF/Io04mjgYjSyieu5X6wJ+uZF/UnyxxmmzNFzIpgjO/AXZI3Zp+62T
ZQXbHm/D86Equhb/7+3UIuKfC01T/Ak0QBjNNTH1pKJ0Z98DnWmDx2KPpULIHq5i44A4AR
K+XuH+8QZl8YrnjupC8e52JIgc9TNrkPDmXnybMc7f0BZrByeInmsi7cRsISacdBytpTa0
8AAAdIl6clMJenJTAAAAAHc3NoLXJzYQAAAgEA5BJQ0hqe1cn+pUrp8dHmbqHJAGJGgtZu
RgPmQ4mvRt4EsOd0EPfaiAdDyum0aAws6whlC5StyfbEVG0ei1C+kcaPJegG2wYY14P8lf
8XjU9zEP/btDtnXYJV51s+hV8PIEyyN81b+W06BGtbBpQVQrr13fEHfhEUafTfa7NiUB6S
CKPDpRZP2/gylmxjc56q+AtYZBIygS78XY1vsHU1uNTnJd9YqFY73TYTQIiQBCIhn59Lgr
KO0IYBVv3DjzshpZ8DhAZvivZMgAK93XR2tTurjJABWWne35jEkoNv6Syp5CEab59MD1aB
nQIT1rNS0VcwwFUl+jWI1OzuTGifNXraotDrMI6PSpNjppK0KEmWyc0HKQbFNO2/MIrj2f
ez5908CrNhIdPFJNIBSOSNGZWJjvYe7ImsZV5aorNvkJDKIDViswLCjVq6QbLQJiDzPszL
0CjMjNEKWfRHk1i1yIPSZC64kn73yE4rIH4bF/Io04mjgYjSyieu5X6wJ+uZF/Unyxxmmz
NFzIpgjO/AXZI3Zp+62TZQXbHm/D86Equhb/7+3UIuKfC01T/Ak0QBjNNTH1pKJ0Z98DnW
mDx2KPpULIHq5i44A4ARK+XuH+8QZl8YrnjupC8e52JIgc9TNrkPDmXnybMc7f0BZrByeI
nmsi7cRsISacdBytpTa08AAAADAQABAAACAQC2me95eHTJKHOn9YW+5dY/p2qd0xEvOe2K
Qx793eOmsqVA2d70ouylUmO1t02IrI7eEpeMIRrPg7IHAmKdGiWp4zbDG7U5cPU8v+DgWx
+JNR4kcyV9dL46gNq0ZDp3X/dlXeKmiNXlqszzstxrNO6cwcGOU6czCQu2Fac3vKSvDvrO
zgcbSvTfYiVmiBtL+7JY7AR2ApfLFEpbwJy2w/EiLdtvWBXMmVZOszfQyEW9+XHAMjKrzr
hHPbMe6gfDyo0S5HBVKS3vLWlsaEWJY/CTA9ZCsR1TcE9P6CkiQPe90dOn4dUfn4OvGAyo
H3ywvlxFXTCcHNBONsR57cSRCobEMFD4zBhKqCV5mW3W2cSYuwoR1cYhQLOFYbYSQU6dCQ
FU36PcGH4ksOS+X2YH9zuTYDlYI0xzu3sn9/Xhod0mcW1HXfDYSx1SOnxo0o6JGCR7L9bt
vseRm8vlEsUDhlbmdXHuH8g2HkNIfOd4+5m82LmNs8YZaaUSQBwUAmVGQcdOFQQnpZLZgB
oBraXp+IWlXYXqjwH0KjRd4U0TA0w8Qn8nlWZJzd3vzpe1JnBaAISPdPSEBTiY6ayuI/AJ
R94YmIXShh/F7i7TIYFsliPpEtyKGBza01Au9Eqan/QjmbDSB8+fr7wqWGZ3TMA05iHl2n
FSvBmewKI37l26u4wF+QAAAQEAk4Vb6sgiX852DGfZmHaKhnZVLsEXmZVyojACfppgzZNc
MEr0H5+FtbDffBQDOAvbFCZYvWPOnhWwNCqLNKLybf3vzOECjcZa4MQkzJ+lfHlbhBSOXA
XYiY5HISQFUvmXBqo5Qo43YZPbxPHAkROXNoQgJm/0GG7HKdog9aUaCI8WIErfDH/LePPU
QsuXr0RYB1EVTgejvo9p7pXXtjvPzgShQHG1uU5i0lPXc8DtI74vOuPZgj3IohWGPdZ7oi
lwKsR8YTErirZo5JbkgotdSVMiyLNN0s4u7Edm6gADfAOf3YvIAc8WBuPkP3kdG1P90a1R
jaP9c2/bmNKZmKF2CwAAAQEA/iSS1hnvqmeLpcXcLQqtSMP6Dn59cNlFrfEC2mT7clU4if
lGczsA/auH+G6vMMR5ZU4fuCr4Fs3556/UcmU3NB8WGdNAcazkYJC8wf1Bdr/7TADJ6Vzf
Pxwk3Byo3tqtCGkC4QBJ3Gke3CV7O8712tSLrgVH46dB7CRFB4RAOwUCvrVv1YqbLXCEP5
RVULbwUfOBjYFHSi4KbxMiIV55VxGhqRJ9SeaizHcnlqXyaqQZQBp/RCIPnr8FMNDCMsSx
mzLFePyzojrJI+qsr1YSrro102XNsiHPoumyP2s5QX1HRatxNhtCGVp/rFRYYhEPvigz+a
BKjr2Z3g5Zm5qjJQAAAQEA5bz4ahb21l3sFS6W9gBt9rck2jFD0AP/L/sfeHPU3hXyNwNr
ojffM1Qb9rPX5aNtF8LTpDYlhVdAwNJ2l2wSV5SveLY9B+qn6N+IzNIdQvDSSDjJZlbE96
ceJ9BVReiHt+1soj6ykCM0phq2jyQmBXD3acjt3Nrz9522YlAZKpE+eMsjp2j8ITJCqKPj
6D3SWHkOA+IieSaahg8ORmUviHJYzjLAdrPNPSKnzODhMoTgu5WXtfYkR83yK4fBPpkYEH
7VOYrPNUNnge9Een2wqnMO5xDdfMSS6iNnqMG9SX69xBZq+LKRmX34y97JvxVwt6+nyyLn
TZHxG+EsksbEYwAAABFzX21vbG9uZXlAYW9sLmNvbQ==
-----END RSA PRIVATE KEY-----




