# Applications to install

general:
  local_home: "{{ lookup('env', 'HOME') }}"

# homebrew


applications:
    - git
    - tree
    - curl
    - wget
    - vim
    

# Homebrew cask

cask:
    - google-chrome
    - slack
    - iterm2
    - caffeine
    - docker
    - vagrant
    - virtualbox
    - emacs
    - spotify
    - postman


# Downloads not in homebrew

downloads:
  zoom:
    name: Zoom
    url: https://zoom.us/support/download?os=mac
    dest: "{{general.local_home}}/Downloads/zoom.pkg"

