# Applications to install

general:
  local_home: "{{ lookup('env', 'HOME') }}"

# homebrew


applications:
    - git
    # - tree
    # - curl
    # - wget
    # - vim
    #- maven java
    # - openssl
   # - direnv need java
    

# Homebrew cask

cask:
    # - google-chrome
    # - slack
    # - iterm2
    # - docker
    # - docker-compose
    # - vagrant
    #- virtualbox #causing issues
    - emacs
    # - postman

github:  #currently working on
  - platform
  - consumer-ui
  - trizic-ops
  - containers
  - api-docs-advisor
  - api-docs-consumer
  - custodianservices
  - td-api-java-lib
  - client-billing
  - messaging-common


downloads:
  zoom:
    name: Zoom
    url: https://zoom.us/support/download?os=mac
    dest: "{{general.local_home}}/Downloads/zoom.pkg"

git_ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHwYBqBTpRdFXQtTVzgV5RclpwE1g8NnVDOPTLqPddIbg5VxxKasRFt0M9EcWfuhuZuTX5cWKck51BLYNQ	U4w9TXONuK0LwuZ+6VNJwyRrow6eWmKZaYE66x5EpB1ngMmTgIGVQezqGASOcb1vOtDcnW5IIVA/UGaLNUuOC3lNXGxLOvrnijFFcswlWuemORuBywljTaAub34bnYdwx5a81dq0hXzF	3vje45CJmtkyjJK2LK/xqRqBk5DVQyWNwG7k6Gbzd/Ar+2IiOPsXlZ2vI9eFcPSOgqxvzfuXUAi12QmbCyud1X/KFV+ovm4ZZm8UN37I8bCYuMkVz65Cut1w0ChHO4ua0Rj+flOIj8KA	CLwTq7H4OddY6qLhMX9ksGshE6njP/daK9/ASnNBN4DooaWfvfBDw+pp4fC0/Rb/a9p8gKVqE/9QV8eqQH3kSd+R6B6OlFXROqEa0MP5RSL++uiZ2OTBJ72PMJWNVPuM1aXwoxBMmeCl	o8ClPDE8Sx3At7hM+/FpkmMCx2SA4IvQSKoKHz3m6RzWdFyL8kpTwkR0YoE5EpWw6mSUKtoC4HGkZ9kMiP6pZ9BJWU88N5QWhAfVpOwMEBo+ElDKn3OAQiJHw42D6uFFLo93+BdPwogJ	KDeP0QN+geZAMrtSXUVzSvBgGq1kNTclrYedpm4bMw==s_moloney@aol.com





git_ssh_key: 
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKgIBAAKCAgEAx8GAagU6UXRV0LU1c4FeUXJacBNYPDZ1Qzj0y6j3XSG4OVcc
  SmrERbdDPRHFn7obmbk1+XFinJOdQS2DUFOMPU1zjbitC8LmfulTScMka6MOnlpi
  mWmBOuseRKQdZ4DJk4CBlUHs6hgEjnG9bzrQ3J1uSCFQP1BmizVLjgt5TVxsSzr6
  54oxRXLMJVrnpjkbgcsJY02gLm9+G52HcMeWvNXatIV8xd743uOQiZrZMoyStiyv
  8akagZOQ1UMljcBu5Ohm83fwK/tiIjj7F5WdryPXhXD0joKsb837l1AItdkJmwsr
  ndV/yhVfqL5uGWZvFDd+yPGwmLjJFc+uQrrdcNAoRzuLmtEY/n5TiI/CgAi8E6ux
  +DnXWOqi4TF/ZLBrIROp4z/3WivfwEpzQTeA6KGln73wQ8PqaeHwtP0W/2vafICl
  ahP/UFfHqkB95EnfkegejpRV0TqhGtDD+UUi/vromdjkwSe9jzCVjVT7jNWl8KMQ
  TJngpaPApTwxPEsdwLe4TPvxaZJjAsdkgOCL0EiqCh895ukc1nRci/JKU8JEdGKB
  ORKVsOpklCraAuBxpGfZDIj+qWfQSVlPPDeUFoQH1aTsDBAaPhJQyp9zgEIiR8ON
  g+rhRS6Pd/gXT8KICSg3j9EDfoHmQDK7Ul1Fc0rwYBqtZDU3Ja2HnaZuGzMCAwEA
  AQKCAgAaxTz/eGnjZrLlgJOEQk8wnSGvqXgGwcmfU6/C54cXLSCyVpFNC9f3++J/
  +bTBfkCarm6kWmS71TCa/o19o2TFBm85DAns7JbVZVGrLgLghf68jCJwquoNylrJ
  GjFyoJjjMrKrHSWyDbv2lxmrIXfCSTrxYb2Obqj/eQoCJFmCW6OLxYDArQ2DYCop
  y3AGH9sm3t4IN+wCrSB6dPckzyrNbd+cl9Mr9YDm5hqFxoHbO2miDoUZ3u7VdMBR
  RGlxANwbw2WgtW8zhcIWEgrck0mJokUM9iFgQ/T2GuXf1nMEY+zcoXeb9HPm0kx6
  oeLBdq/mRrWwGmvvW7xfNvEEsmRgsBDxsER4olK9IK2e5VHaCaAUFiBxhCbgnBZ9
  67BH+PbOlRuOqhLy6NaqlJIeP2fnEcrF1SO42gqZzlvyBUwznAws78erW2CXq/44
  vZYPgP7xqkKM/FxkXII3SSybHMp3K0ECnDhwave9V1mtppOrUpA4g21ZA/fWekC7
  LeCI8mAmHCHwwjLC6jz6XeShRn0bCuySDj07kXr9Xnt8m7BYnF8Ti/K4O70mHkkN
  3aCMQOipPMKTUqhuwg3vFE5ah2m0V8yelkbN+pJfhcL58myynIqpp5NmN9/tzjmH
  FMxHlQ5KeY9uUxQg8gd2j9hcJwbMU1cxQjZLuY1OMDE9NCe/uQKCAQEA/cFTkFBb
  6JN7Q7VafsINvXPLpa2xmB58GoxtI0nKJ7n5O61nfJGNCP0eqYvMkVOTe+SHN/4Z
  pqpmTwju5U6lVTI/IYTxOqSPetyDGU4OSkUlvNwAoXn4GU1jCpKMMX8RntDcemul
  9B+M9aDNEt/tnDdIMy5MByRxJp5zuzzKrUQ0cmhtviTJPC1kDj0W++z787bJlU/F
  Gn2sjgZ1sd2PPE8mw8l4iSpNgQWV1bCPJF8gYp9pIe9olyFGvvszensZCstdwmrJ
  3Co4c5/La2aHjdauOaFnH1fRCHYDIPKOqa0YuZU1+oCk1yjshd0Ra9yYdjCBuMtN
  AzTEoprB//7aPQKCAQEAyYXiWWkY4I2wmVqKqzoeTpoMNRpot3RYKjU7iKalfHTk
  dTPISRP8TXtSSGwFwgIfYTgdZLOzyJBvgdUUUSNLPsyWNq6XA9pFYNeLbNNKeBWy
  LLYHUfv5+2PBPFRz4rbnN8Uj9eQ0I8kjOOpJgUosSkN1pMoATTks4PTqR4OXRwR3
  trjr+YV5gz65t6NuHa34ccJJDimoAl707O2BCryuO+AHMxk3EK46IGGkOACtuWwj
  nkha75AowSg6wzWNC3BDlkwNAUXg1xfr92amnP2ygsQlnQMdmmtpiOYXEHczX6Dc
  ypE3Oa+XLXPyMq9xfbJTHhkSItJS5K5MA1WhdfbSLwKCAQEAqlSV2f4G44PzrsxR
  9VoezPeoUAradeiol02BiLlkR+xOvt8z4ur0h38YkOg1Jau7COOqXExlPXmN+Sle
  6m8zDZAPzlklb568bNUN7vN1JidqIG5wwfNUNO+8NoGONz87PaanCEmv+MEg5lPM
  tAm5vi1henFuOTEd/rVHq/wvc8Sfi9hLKeIZbhpt2hzpi6tUqBAfGemUvaZ0KFVv
  tTeqiOn8dFmNXk0V/zAXlnvQabKs02Z7tHq2cxO0IEgQEvwEIDnIMtNpsi5o/Dvb
  2LjW7r+W7TpJNUHGH27PxNLsLjrxqMjelcq6W26t7WEp64QElvkSak+U3z0RbLCC
  3mpcZQKCAQEAttPJS7amhCrn2ekjvz5l+oeVpaPE9xMNXZWX4lzV6/icv5vwDCSe
  lKjaOKwP+Tg1wdzIBfFmnQI0t8RZv1bW0C2J5ig1B6DBqp9CdcOnXxTH5fpq371L
  yP9yc0pnLHslgBpRiqazivfTBbLAZxSk4+cZ1xwQc/74MUrhNWo0F5D9Dv/rzh+C
  40hH80vI/hI0QPizkK7IJwaBDGZY2SXeqKGRxpEMvQxj3bbX5prvATcThWk9XvQZ
  lUvrK+jsgkEigDuU3N/JoTqpsHUnmWwsxKgxO6Z0+ACU6UdeC2kpaYumY/yk7qfX
  7ruvMr6qpw/eioLSSlcoLyHWAnxwlHYNrwKCAQEAsyqgJvxkiLznTOl74sTDQee+
  x8sEwwT+KLMZKJo5k73qE0DfANO5nqsBnc2Ou6aYo7AjBh1kum2N/xgQKMtB0hpd
  VJQ7hAbPMXw760EiNQV8DlUKUCpZjTqONcdB4V4bU9+mB9WHU73+BqOc4dTuZV5x
  PtxA6HrACIoH0I0rG82nT/dTrLVc7DAQrHuujNxtPxlblcj7OlpxB0B1YwG2rCh+
  2axBhWjBy5QAUjhi7ZFGW4Pd1+3jx3Ax0L/0KhUL1C4ZVZ1ZSApR3i2dfxw0NUUX
  nDBfJpeJ1hN/uSjuT0sZRU4K+o1ibpEoaEzQZQy56wC3perkIqsh0Xc8N8O3pw==
  -----END RSA PRIVATE KEY-----




