# Applications to install

general:
  local_home: "{{ lookup('env', 'HOME') }}"

# homebrew


applications:
    - git
    - tree
    - curl
    - wget
    - vim
    #- maven java
    - openssl
   # - direnv need java
    

# Homebrew cask

cask:
    - google-chrome
    - slack
    - iterm2
    - docker
    - docker-compose
    - vagrant
    - virtualbox #causing issues
    - emacs
    - postman

github:  #currently working on
  - platform
  - consumer-ui
  - trizic-ops
  - containers
  - api-docs-advisor
  - api-docs-consumer
  - custodianservices
  - td-api-java-lib
  - client-billing
  - messaging-common


downloads:
  zoom:
    name: Zoom
    url: https://zoom.us/support/download?os=mac
    dest: "{{general.local_home}}/Downloads/zoom.pkg"

