

- name: application installs
  include: homebrew.yml
  

- name: Installing Homebrew Apps
  homebrew:
    name: "{{item}}"
    state: latest
  with_items: "{{applications}}"

- name: Installing Homebrew Casks
  homebrew_cask:
    name: "{{item}}"
    state: installed 
  with_items: "{{cask}}"
- name: Installing virtualbox
  command: brew cask install --force virtualbox

- name: getting downloads
  get_url:
    url: "{{item.value.url}}"
    dest: "{{item.value.dest}}"
  with_dict: "{{downloads}}"    

