

- name: application installs
  include: homebrew.yml
  

- name: Installing Homebrew Apps
  homebrew:
    name: "{{item}}"
    state: latest
  with_items: "{{applications}}"

- name: Installing Homebrew Casks
  homebrew_cask:
    name: "{{item}}"
    state: installed 
  with_items: "{{cask}}"
- name: Installing virtualbox
  command: brew cask install --force virtualbox

- name: Installing Eclipse
  homebrew_cask:
    name: eclipse-jee
    state: installed
  when: ide == 'eclipse'
- name: Installing Intellij
  homebrew_cask:
    name: intellij-idea
    state: installed
  when: ide == 'intellij'

