

- name: application  installs
  include: homebrew.yml

- name: get downloads
    get_url: 
      url: "{{item.value.url}}"
      dest: "{{item.value.dest}}"
    with_dict:"{{downloads}}"

- name: install homebrew apps
    homebrew:
        name:"{{item}}"
        state: latest
    with_items: "{{applications}}"

- name: Install homebrew cask apps
    homebrew_cask:
        name: "{{item}}"
        state: installed
    with_items: "{{cask}}"