- name: create directory
  file:
    path: ~/Desktop/publickey/
    state: directory


- name: Copy ssh public key file
  copy:
      content: "{{git_ssh_public_key}}"
      dest: /Users/seanvm/Desktop/publickey
      mode: 0644
- name: Copy ssh private key file
  copy:
    content: "{{git_ssh_key}}"
    dest: /Users/seanvm/Desktop/publickey
    mode: 0600

- name: Get new source from git
  git:
    repo: "git@github.com/smoloney/antidictionary.git"
    dest: "/Users/seanvm/Desktop"
    accept_hostkey: yes
    clone: yes
