- name: create directory
  file:
    path: ~/Desktop/publickey/
    state: directory

- name: create directory 2
  file:
    path: "{{item}}"
    state: directory
    owner: "{{general.local_user}}"
    #group: "{{general.local_group}}"
    #mode: 0775

  with_items: "{{filePaths}}"


# - name: Copy ssh public key file
#   copy:
#       content: "{{git_ssh_public_key}}"
#       dest: /Users/seanvm/Desktop/publickey
#       mode: 0644
# - name: Copy ssh private key file
#   copy:
#     content: "{{git_ssh_key}}"
#     dest: /Users/seanvm/Desktop/publickey
#     mode: 0600

- name: Get new source from git
  git:
    repo: ssh://git@github.com/smoloney/antidictionary.git
    dest: /Users/seanvm/Desktop/GitClone/
    accept_hostkey: yes
    clone: yes


# - name: create directory if they don't exist
#   file:
#     path: "{{ item }}"
#     state: directory
#     owner: root
#     group: root
#     mode: 0775
#   with_items:
#     - /data/directory
#     - /data/another