- name: create directory
  file:
    path: ~/Desktop/publickey/
    state: directory

- name: create directory 2
  file:
    path: "{{item}}"
    state: directory
    owner: "{{general.local_user}}"
    #group: "{{general.local_group}}"
    #mode: 0775

  with_items: "{{filePaths}}"


# - name: Copy ssh public key file
#   copy:
#       content: "{{git_ssh_public_key}}"
#       dest: /Users/seanvm/Desktop/publickey
#       mode: 0644
# - name: Copy ssh private key file
#   copy:
#     content: "{{git_ssh_key}}"
#     dest: /Users/seanvm/Desktop/publickey
#     mode: 0600

# - name: Get new source from git
#   git:
#     repo: "ssh://git@github.com/trizic/{{item.repo}}.git"
#     dest: "{{item.dest}}"
#     accept_hostkey: yes
#     clone: yes
#   with_items: 
#     - { 
#         repo: "{{github}}",
#         dest: "{{filePaths}}"
#     }

- name: Cloning Platform
  git:
    repo: "ssh://git@github.com/trizic/platform.git"
    dest: ~/Documents/Trizic/platform
    accept_hostkey: yes
    clone: yes
- name: Cloning Consumer UI
  git:
    repo: "ssh://git@github.com/trizic/consumer-ui.git"
    dest: ~/Documents/Trizic/consumer-ui
    accept_hostkey: yes
    clone: yes
- name: Cloning trizic ops
  git:
    repo: "ssh://git@github.com/trizic/trizic-ops.git"
    dest: ~/Documents/Trizic/trizic-ops
    accept_hostkey: yes
    clone: yes
- name: Cloning Containers
  git:
    repo: "ssh://git@github.com/trizic/containers.git"
    dest: ~/Documents/Trizic/containers
    accept_hostkey: yes
    clone: yes
- name: Cloning api-docs-advisor
  git:
    repo: "ssh://git@github.com/trizic/api-docs-advisor.git"
    dest: ~/Documents/Trizic/api-docs-advisor
    accept_hostkey: yes
    clone: yes
- name: Cloning Api docs consumer
  git:
    repo: "ssh://git@github.com/trizic/api-docs-consumer.git"
    dest: ~/Documents/Trizic/api-docs-consumer
    accept_hostkey: yes
    clone: yes
- name: Cloning Custodian Services
  git:
    repo: "ssh://git@github.com/trizic/custodianservices.git"
    dest: ~/Documents/Trizic/custodianservices
    accept_hostkey: yes
    clone: yes
- name: Cloning TD-api-java-lib
  git:
    repo: "ssh://git@github.com/trizic/td-api-java-lib.git"
    dest: ~/Documents/Trizic/td-api-java-lib
    accept_hostkey: yes
    clone: yes
- name: Cloning Client billing
  git:
    repo: "ssh://git@github.com/trizic/client-billing.git"
    dest: ~/Documents/Trizic/client-billing
    accept_hostkey: yes
    clone: yes

- name: Cloning Messaging common
  git:
    repo: "ssh://git@github.com/trizic/messaging-common.git"
    dest: ~/Documents/Trizic/messaging-common
    accept_hostkey: yes
    clone: yes

- name: Download Java
  command: "wget -q -O java.dmg --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}}"

#   - name: Unpack archive
#     command: "tar -zxf {{java_archive}} -C {{download_folder}} creates={{java_name}}"

#   - name: Fix ownership
#     file: state=directory path={{java_name}} owner=root group=root recurse=yes

#   - name: Make Java available for system
#     command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

#   - name: Clean up
#     file: state=absent path={{java_archive}}