
- name: Create bash profiles
  file:
    path: ~/.bashrc
    state: touch


- name: Download JDK
  get_url:
    url:  "{{ download_url }}"
    headers: "{{java_header}}"
    dest: "{{java_archive}}"

- name: Download JCE
  get_url: 
    url: "{{jce_download_url}}"
    headers: "{{java_header}}"

    dest: "{{java_name}}/{{jce_zip_file}}"



- name: mount the downloaded dmg
  shell: hdiutil attach ~/jdk-8u5.dmg


- name: install the pkg file from the dmg
  become: yes
  become_method: sudo
  shell: >
    installer
    -pkg "/Volumes/JDK {{ java_version }} Update {{ java_subversion }}/JDK {{ java_version }} Update {{ java_subversion }}.pkg"
    -target /

- name: unmount the downloaded dmg
  shell: hdiutil detach "/Volumes/JDK {{ java_version }} Update {{ java_subversion }}"

- name: Setting java home
  lineinfile: "dest=~/.bashrc line='export JAVA_HOME={{java_home}}'
    insertafter='EOF' state=present"

- name: unzip JCE
  unarchive:
    src: "{{java_name}}/{{jce_zip_file}}"
    dest: "{{java_name}}/"
    copy: no
    creates: "{{ java_name }}/jce"
# - name: Copy JCE Jars
#   copy:
#     sudo: yes
#     src: /var/root/UnlimitedJCEPolicyJDK8/{{item}}"
#     dest: "{{ java_home}}/jre/lib/security/{{item}}"
#     remote_src: True
#     #mode: 0664
#   become: true
#   with_items:
#     - US_export_policy.jar
#     - local_policy.jar
- name: install JCE policies
  copy:
   #sudo: yes
   src: "{{ java_name }}/{{ jce_folder }}/{{ item }}"
   dest: "{{ java_home }}/jre/lib/security/{{ item }}"
   remote_src: True
   mode: 0664
  become: true
  with_items:
    - local_policy.jar
    - US_export_policy.jar




