
- name: Create bash profiles
  file:
    path: ~/.bashrc
    state: touch


- name: Download JDK
  get_url:
    url:  https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-macosx-x64.dmg
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: "{{java_archive}}"


- name: mount the downloaded dmg
  shell: hdiutil attach ~/jdk-8u5.dmg


- name: install the pkg file from the dmg
  become: yes
  become_method: sudo
  shell: >
    installer
    -pkg "/Volumes/JDK {{ java_version }} Update {{ java_subversion }}/JDK {{ java_version }} Update {{ java_subversion }}.pkg"
    -target /

- name: unmount the downloaded dmg
  shell: hdiutil detach "/Volumes/JDK {{ java_version }} Update {{ java_subversion }}"

- name: Setting java home
  lineinfile: dest=~/.bashrc line='export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home'
    insertafter='EOF' state=present